name: Percy snapshot tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Build Next.js
        run: npm run build
      - name: Run tests
        uses: percy/exec-action@v0.3.1
        with:
          custom-command: "npm run percy:ci"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
